version: '3.7'

services:

  # nginx setup
  nginx:
    build: ./requirements/nginx/
    image: nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - web:/var/www/html
    env_file:
      - env.env
    depends_on:
      - wordpress
    restart : always

  # mariadb setup
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    networks:
      - inception
    ports:
      - 3306:3306
    env_file:
      - env.env
    volumes:
      - db-data:/var/lib/mysql
    restart : always

  #wordpress setup
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    networks:
      - inception
    ports:
      - 9000:9000
    env_file:
      - env.env
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    restart: always



# network that holds all my containers
networks:
  inception:
    name : inception
    driver : bridge

# volumes that hold all my wordpress and databases files
volumes:
  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yaskour/data/web
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yaskour/data/db
