version: '3.7'

services:

  # nginx setup
  nginx:
    build: ./requirements/nginx/
    image: nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/web:/var/www/html
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - env.env
    depends_on:
      - wordpress
    restart : always

  # mariadb setup
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    networks:
      - inception
    ports:
      - 3306:3306
    env_file:
      - env.env
    volumes:
      - ./requirements/mariadb/db/:/var/lib/mysql/word_db
    restart : always

  #wordpress setup
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    networks:
      - inception
    env_file:
      - env.env
    depends_on:
      - mariadb
    volumes:
      - ./requirements/nginx/web:/var/www/html
    restart: always



# network that holds all my containers
networks:
  inception:
    name : inception
    driver : bridge
