version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/web:/var/www/html
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
